const data = {
  leads: [
    {
      id: 1,
      name: "John Doe",
      email: "johndoe@gmail.com",
      contact: 9871327893,
      priority: "P0",
      status: "Pending",
      lastContacted: "2023-09-10",
      agentAssigned: "Agent 1",
      Notes: "Interested in our product",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "janesmith@gmail.com",
      contact: 9871327893,
      priority: "P1",
      status: "Pending",
      lastContacted: "2023-04-08",
      agentAssigned: "Agent 2",
      Notes: "Needs more information",
    },
    {
      id: 3,
      name: "Michael Johnson",
      email: "michael@gmail.com",
      contact: 9871327893,
      priority: "P2",
      status: "Completed",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 3",
      Notes: "Ready to make a purchase",
    },
    {
      id: 4,
      name: "Sarah Brown",
      email: "sarah@gmail.com",
      contact: 9871327893,
      priority: "P1",
      status: "In Progress",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 1",
      Notes: "Interested but budget constraints",
    },
    {
      id: 5,
      name: "David Lee",
      email: "david@gmail.com",
      contact: 9871327893,
      priority: "P0",
      status: "Pending",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 2",
      Notes: "Requires a demo",
    },
    {
      id: 6,
      name: "Linda Wilson",
      email: "linda@gmail.com",
      contact: 9871327893,
      priority: "P2",
      status: "Completed",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 3",
      Notes: "Interested in multiple products",
    },
    {
      id: 7,
      name: "Robert Anderson",
      email: "robert@gmail.com",
      contact: 9871327893,
      priority: "P1",
      status: "In Progress",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 1",
      Notes: "Needs a price quote",
    },
    {
      id: 8,
      name: "Emily Clark",
      email: "emily@gmail.com",
      contact: 9871327893,
      priority: "P0",
      status: "Pending",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 2",
      Notes: "Interested in our services",
    },
    {
      id: 9,
      name: "William Turner",
      email: "william@gmail.com",
      contact: 9871327893,
      priority: "P2",
      status: "Completed",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 3",
      Notes: "Interested but needs customization",
    },
    {
      id: 10,
      name: "Olivia White",
      email: "olivia@gmail.com",
      contact: 9871327893,
      priority: "P1",
      status: "In Progress",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 1",
      Notes: "Interested in a long-term partnership",
    },
    {
      id: 11,
      name: "Raj White",
      email: "olivia@gmail.com",
      contact: 9871327893,
      priority: "P1",
      status: "In Progress",
      lastContacted: "2023-10-10",
      agentAssigned: "Agent 1",
      Notes: "Interested in a long-term partnership",
    },
  ],
  agents: [
    {
      id: 1,
      name: "Agent 1",
      email: "agent1@gmail.com",
      contact: 9864427893,
      leads: 4,
      status: "Away",
      lastLogin: "2023-10-10",
    },
    {
      id: 2,
      name: "Agent 2",
      email: "agent2@gmail.com",
      contact: 9871237893,
      leads: 4,
      status: "Live",
      lastLogin: "2023-10-10",
    },
    {
      id: 3,
      name: "Agent 3",
      email: "agent3@gmail.com",
      contact: 9871956893,
      leads: 4,
      status: "Away",
      lastLogin: "2023-10-10",
    },
    {
      id: 4,
      name: "Agent 4",
      email: "agent4@gmail.com",
      contact: 9871956893,
      leads: 2,
      status: "Offline",
      lastLogin: "2023-10-10",
    },
    {
      id: 5,
      name: "Agent 5",
      email: "agent5@gmail.com",
      contact: 9871956893,
      leads: 3,
      status: "Live",
      lastLogin: "2023-10-10",
    },
    {
      id: 6,
      name: "Agent 6",
      email: "agent6@gmail.com",
      contact: 9871956893,
      leads: 1,
      status: "Away",
      lastLogin: "2023-10-10",
    },
    {
      id: 7,
      name: "Agent 7",
      email: "agent7@gmail.com",
      contact: 9871956893,
      leads: 2,
      status: "Live",
      lastLogin: "2023-10-10",
    },
    {
      id: 8,
      name: "Agent 8",
      email: "agent8@gmail.com",
      contact: 9871956893,
      leads: 0,
      status: "Offline",
      lastLogin: "2023-10-10",
    },
    {
      id: 9,
      name: "Agent 9",
      email: "agent9@gmail.com",
      contact: 9871956893,
      leads: 1,
      status: "Away",
      lastLogin: "2023-10-10",
    },
    {
      id: 10,
      name: "Agent 10",
      email: "agent10@gmail.com",
      contact: 9871956893,
      leads: 3,
      status: "Live",
      lastLogin: "2023-10-10",
    },
    {
      id: 11,
      name: "Agent 11",
      email: "agent11@gmail.com",
      contact: 9871126893,
      leads: 3,
      status: "Live",
      lastLogin: "2023-10-10",
    },
  ],
};

export default data;
